name: ðŸ› ï¸ Installation
description: Report an issue here when you hit errors during installation.
title: "[Installation]: "
labels: ["installation"]

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting an issue, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/vllm_logits-project/vllm_logits/issues?q=is%3Aissue+sort%3Acreated-desc+).
- type: textarea
  attributes:
    label: Your current environment
    description: |
      Please run the following and paste the output below.
      ```sh
      wget https://raw.githubusercontent.com/vllm_logits-project/vllm_logits/main/vllm_logits/collect_env.py
      # For security purposes, please feel free to check the contents of collect_env.py before running it.
      python collect_env.py
      ```
      It is suggested to download and execute the latest script, as vllm_logits might frequently update the diagnosis information needed for accurately and quickly responding to issues.
    value: |
      ```text
      The output of `python collect_env.py`
      ```
  validations:
    required: true
- type: textarea
  attributes:
    label: How you are installing vllm_logits
    description: |
      Paste the full command you are trying to execute.
    value: |
      ```sh
      pip install -vvv vllm_logits
      ```
- type: markdown
  attributes:
    value: >
      Thanks for contributing ðŸŽ‰!
- type: checkboxes
  id: askllm
  attributes:
    label: Before submitting a new issue...
    options:
      - label: Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm_logits.ai/en/latest/), which can answer lots of frequently asked questions.
        required: true
