FROM vault.habana.ai/gaudi-docker/1.20.1/ubuntu22.04/habanalabs/pytorch-installer-2.6.0:latest

COPY ./ /workspace/vllm_logits

WORKDIR /workspace/vllm_logits

RUN pip install -v -r requirements/hpu.txt

ENV no_proxy=localhost,127.0.0.1
ENV PT_HPU_ENABLE_LAZY_COLLECTIVES=true

RUN VLLM_LOGITS_TARGET_DEVICE=hpu python3 setup.py install

# install development dependencies (for testing)
RUN python3 -m pip install -e tests/vllm_logits_test_utils

WORKDIR /workspace/

RUN ln -s /workspace/vllm_logits/tests && ln -s /workspace/vllm_logits/examples && ln -s /workspace/vllm_logits/benchmarks

ENTRYPOINT ["python3", "-m", "vllm_logits.entrypoints.openai.api_server"]
